package dev.danielmillar.voicesentinel.notify.discord;

import dev.danielmillar.voicesentinel.moderation.rules.RuleMatch;

import java.time.Duration;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Text is rendered from complete escape atoms and balanced spans, even when truncated. */
final class DiscordText {
    private static final String MARKDOWN = "\\*_~`|>#-[]()";
    private static final Pattern PLACEHOLDER = Pattern.compile("\\{(player|action|duration|id|server)}");
    private record Span(String text, String open, String close, boolean escaped) {}
    private record Prefix(String text, boolean complete) {}
    private final List<Span> spans = new ArrayList<>();

    DiscordText append(String text) { return span(text, "", ""); }
    // Used only with UUIDs generated by the plugin; escaping inside a code span would display backslashes.
    DiscordText code(String text) { spans.add(new Span(text, "`", "`", false)); return this; }
    private DiscordText span(String text, String open, String close) {
        spans.add(new Span(text, open, close, true));
        return this;
    }

    static DiscordText plain(String text) { return new DiscordText().append(text); }

    static DiscordText highlighted(String text, List<RuleMatch> matches, boolean spoiler) {
        DiscordText result = new DiscordText();
        List<int[]> ranges = new ArrayList<>();
        for (RuleMatch match : matches) {
            int start = Math.max(0, Math.min(text.length(), match.start()));
            int end = Math.max(start, Math.min(text.length(), match.end()));
            if (end > start) ranges.add(new int[]{start, end});
        }
        ranges.sort(Comparator.comparingInt(range -> range[0]));
        List<int[]> merged = new ArrayList<>();
        for (int[] range : ranges) {
            if (!merged.isEmpty() && range[0] < merged.getLast()[1]) {
                merged.getLast()[1] = Math.max(merged.getLast()[1], range[1]);
            } else merged.add(range);
        }
        int position = 0;
        for (int[] range : merged) {
            result.append(text.substring(position, range[0]));
            result.span(text.substring(range[0], range[1]), spoiler ? "||**" : "**", spoiler ? "**||" : "**");
            position = range[1];
        }
        return result.append(text.substring(position));
    }

    String render(int max) {
        if (max <= 0) return "";
        StringBuilder output = new StringBuilder();
        long remainingSpans = spans.stream().filter(span -> !span.text().isEmpty()).count();
        for (Span span : spans) {
            if (span.text().isEmpty()) continue;
            remainingSpans--;
            int markers = span.open().length() + span.close().length();
            // Reserve an ellipsis whenever more nonempty spans follow.
            int budget = max - output.length() - markers - (remainingSpans > 0 ? 1 : 0);
            Prefix escaped = prefix(span.text(), Math.max(0, budget), span.escaped());
            if (budget >= 0 && escaped.complete()) {
                output.append(span.open()).append(escaped.text()).append(span.close());
                continue;
            }
            budget = max - output.length() - markers - 1;
            Prefix truncated = prefix(span.text(), Math.max(0, budget), span.escaped());
            if (!truncated.text().isEmpty()) output.append(span.open()).append(truncated.text()).append(span.close());
            if (output.length() < max) output.append('…');
            return output.toString();
        }
        return output.toString();
    }

    private static Prefix prefix(String text, int max, boolean escapeMarkdown) {
        StringBuilder output = new StringBuilder(Math.min(text.length(), max));
        for (int index = 0; index < text.length();) {
            int cp = text.codePointAt(index);
            int width = Character.charCount(cp);
            boolean lineStart = index == 0 || text.charAt(index - 1) == '\n';
            boolean escape = escapeMarkdown && cp <= Character.MAX_VALUE && MARKDOWN.indexOf((char) cp) >= 0 && (cp != '-' || lineStart);
            if (output.length() + width + (escape ? 1 : 0) > max) return new Prefix(output.toString(), false);
            if (escape) output.append('\\');
            output.appendCodePoint(cp);
            index += width;
        }
        return new Prefix(output.toString(), true);
    }

    static String template(String template, Map<String, String> values) {
        Matcher matcher = PLACEHOLDER.matcher(template);
        StringBuilder result = new StringBuilder();
        while (matcher.find()) matcher.appendReplacement(result, Matcher.quoteReplacement(values.getOrDefault(matcher.group(1), "")));
        matcher.appendTail(result);
        return result.toString();
    }

    static String duration(Duration duration) {
        if (duration == null) return "";
        long seconds = Math.max(0, duration.getSeconds());
        long[] units = {86_400, 3_600, 60, 1};
        String[] suffixes = {"d", "h", "m", "s"};
        StringJoiner result = new StringJoiner(" ");
        for (int index = 0; index < units.length; index++) {
            long count = seconds / units[index];
            seconds %= units[index];
            if (count > 0) result.add(count + suffixes[index]);
        }
        String value = result.toString();
        return value.isEmpty() ? "0s" : value;
    }
}
